# ビルド成果物で動作確認したい時のdocker-composeファイル
version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - 8880:80
    volumes:
      - ./log/nginx/:/var/log/nginx/
      - ./nginx/nginx-static.conf:/etc/nginx/nginx.conf
      - ./wasm/pkg:/wasm
      - ./vue/cubetrain/dist:/vuedist
    container_name: cubetrain-nginx-static
