version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - 8880:80
    volumes:
      - ./log/nginx/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/wasm:/wasm
      - ./nginx/vuedist:/vuedist
      # - ./wasm/pkg:/wasm
      # - ./vue/cubetrain/dist:/vuedist
    depends_on:
      - vuefront
    container_name: cubetrain-nginx

  vuefront:
    build:
      context: ./vue
      dockerfile: Dockerfile-vue
    ports:
      - 8881:8080
    volumes:
      - ./vue:/vue
    container_name: cubetrain-vuefront
    # command: "/bin/sh"
    tty: true
