AWSTemplateFormatVersion: 2010-09-09
Description: ACFS3 - S3 Static site with CF and ACM (uksb-1qnk6ni7b) (version:v0.5)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Domain
        Parameters:
          - SubDomain
          - DomainName
      - Label:
          default: Certificate
        Parameters:
          - CertificateArn

Mappings:
  Solution:
    Constants:
      Version: 'v0.7'

Parameters:
  SubDomain:
    Description: The part of a website address before your DomainName - e.g. www or img
    Type: String
    Default: www
    AllowedPattern: ^[^.]*$
  DomainName:
    Description: The part of a website address after your SubDomain - e.g. example.com
    Type: String
  CreateApex:
    Description: Create an Apex Alias in CloudFront distribution - yes/no
    Type: String
    Default: 'no'
    AllowedValues: ['yes','no']
  S3BucketName:
    Description: Bucket name for main static resources.
    Type: String
  CertificateArn:
    Description: CertificateArn for cloudfront
    Type: String

Resources:
  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./s3-bucket.yaml
      Parameters:
        S3BucketName: !Ref S3BucketName
      Tags:
        - Key: Solution
          Value: ACFS3

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudfront-site.yaml
      Parameters:
        CertificateArn: !Ref CertificateArn
        DomainName: !Ref DomainName
        SubDomain: !Ref SubDomain
        CreateApex: !Ref CreateApex
        S3BucketRoot: !GetAtt S3BucketStack.Outputs.S3BucketRoot
        S3BucketRootName: !GetAtt S3BucketStack.Outputs.S3BucketRootName
        S3BucketRootArn: !GetAtt S3BucketStack.Outputs.S3BucketRootArn
        S3BucketLogs: !GetAtt S3BucketStack.Outputs.S3BucketLogs
        S3BucketLogsName: !GetAtt S3BucketStack.Outputs.S3BucketLogsName
      Tags:
        - Key: Solution
          Value: ACFS3

Outputs:
  SolutionVersion:
    Value: !FindInMap [Solution, Constants, Version]
  S3BucketLogs:
    Description: Logging bucket
    Value: !GetAtt S3BucketStack.Outputs.S3BucketLogs
  S3BucketRoot:
    Description: Website bucket
    Value: !GetAtt S3BucketStack.Outputs.S3BucketRoot
  S3BucketLogsName:
    Description: Logging bucket name
    Value: !GetAtt S3BucketStack.Outputs.S3BucketLogsName
  S3BucketRootName:
    Description: Website bucket name
    Value: !GetAtt S3BucketStack.Outputs.S3BucketRootName
  CFDistributionId:
    Description: CloudFront distribution
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDistributionId
  CFDistributionName:
    Description: CloudFront distribution
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDistributionName
  CloudFrontDomainName:
    Description: Website address
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDomainName
